from flask import Flask, render_template, request, send_file
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime
from docx import Document

import requests

app = Flask(__name__)


def fetch_facility(ccn):
    url = f"https://data.cms.gov/provider-data/api/1/datastore/query/4pq5-n9py/0?conditions[0][property]=cms_certification_number_ccn&conditions[0][value]={ccn}"

    response = requests.get(url)
    data = response.json()

    if len(data["results"]) == 0:
        return None

    return data["results"][0]


@app.route("/", methods=["GET", "POST"])
def home():
    facility = None
    action = None

    if request.method == "POST":
        ccn = request.form.get("ccn")

        if not ccn:
            return render_template(
                "index.html",
                facility=None,
                form=request.form,
                error="Please enter a CCN before searching or generating a PDF."
            )

        name_override = request.form.get("name_override")
        emr = request.form.get("emr")
        current_census = request.form.get("current_census")
        patient_type = request.form.get("patient_type")
        medelite_history = request.form.get("medelite_history")
        previous_coverage = request.form.get("previous_coverage")
        previous_provider_performance = request.form.get("previous_provider_performance")
        medical_coverage = request.form.get("medical_coverage")

        facility = fetch_facility(ccn)

        if facility is None:
            return render_template(
                "index.html",
                facility=None,
                form=request.form,
                error=f"No facility found for CCN {ccn}. Please check the number and try again."
            )

        action = request.form.get("action")
        today = datetime.now().strftime("%B %d, %Y")

        def text_or_default(value, default="Not Provided"):
            return value if value else default

        if name_override:
            facility["provider_name"] = name_override

        facility["emr"] = emr
        facility["current_census"] = current_census
        facility["patient_type"] = patient_type
        facility["medelite_history"] = medelite_history
        facility["previous_coverage"] = previous_coverage
        facility["previous_provider_performance"] = previous_provider_performance
        facility["medical_coverage"] = medical_coverage
        facility["state_abbrev"] = (
            facility.get("provider_state")
            or facility.get("state")
            or facility.get("provider_state_abbreviation")
            or ""
        )

        if current_census:
            occupancy = round(
                (float(current_census) / float(facility["number_of_certified_beds"])) * 100,
                1
            )
            facility["occupancy"] = occupancy
        else:
            facility["occupancy"] = ""

    if action == "pdf":
            pdf_buffer = BytesIO()
            pdf = canvas.Canvas(pdf_buffer)
            pdf.setTitle("Facility Assessment Snapshot")

            today = datetime.now().strftime("%B %d, %Y")

            # Helpers
            def rating_stars(value):
                rating = int(value) if value else 0
                return "★" * rating + "☆" * (5 - rating)

            # Colors
            ink = (38/255, 56/255, 79/255)
            blue = (72/255, 105/255, 136/255)
            cream = (255/255, 250/255, 246/255)
            sand = (234/255, 223/255, 215/255)
            muted = (110/255, 120/255, 135/255)
            green = (82/255, 122/255, 96/255)
            gold = (198/255, 154/255, 74/255)
            orange = (201/255, 120/255, 82/255)
            red = (173/255, 95/255, 95/255)

            # Background
            pdf.setFillColorRGB(*cream)
            pdf.rect(0, 0, 612, 792, fill=1, stroke=0)

            # Header bar
            pdf.setFillColorRGB(*ink)
            pdf.rect(0, 720, 612, 72, fill=1, stroke=0)

            pdf.setFillColorRGB(1, 1, 1)
            pdf.setFont("Helvetica-Bold", 22)
            pdf.drawString(50, 758, "INFINITE — Managed by MEDELITE")

            pdf.setFont("Helvetica-Bold", 7)
            pdf.drawString(50, 744, "MANAGED BY MEDELITE")

            # Title
            pdf.setFillColorRGB(*ink)
            pdf.setFont("Helvetica-Bold", 22)
            pdf.drawString(50, 685, f"FACILITY ASSESSMENT SNAPSHOT — {facility.get('state_abbrev', '')}")

            pdf.setFillColorRGB(*muted)
            pdf.setFont("Helvetica", 9)
            pdf.drawString(50, 668, f"Generated by INFINITE | MedElite Analytics | {today}")

            # Facility name/address
            pdf.setFillColorRGB(*ink)
            pdf.setFont("Helvetica-Bold", 16)
            pdf.drawString(50, 630, facility["provider_name"])

            pdf.setFont("Helvetica", 10)
            pdf.drawString(50, 614, facility["location"])

            # Card helper
            def draw_card(x, y, w, h, label, value):
                pdf.setStrokeColorRGB(*sand)
                pdf.setFillColorRGB(1, 1, 1)
                pdf.roundRect(x, y, w, h, 12, fill=1, stroke=1)

                pdf.setFillColorRGB(*muted)
                pdf.setFont("Helvetica-Bold", 7)
                pdf.drawString(x + 12, y + h - 18, label.upper())

                pdf.setFillColorRGB(*ink)
                pdf.setFont("Helvetica-Bold", 11)
                pdf.drawString(x + 12, y + 16, str(value))

            # Facility info cards
            current_census_text = facility.get("current_census") or "Not Provided"
            occupancy_text = (f"{facility['occupancy']}%" if facility.get("occupancy") else "Not Calculated")

            draw_card(50, 545, 155, 52, "Certified Beds", facility["number_of_certified_beds"])
            draw_card(220, 545, 155, 52, "Current Census", current_census_text)
            draw_card(390, 545, 155, 52, "Occupancy", occupancy_text)

            draw_card(50, 480, 155, 52, "EMR", text_or_default(facility.get("emr")))
            draw_card(220, 480, 155, 52, "Patient Type", text_or_default(facility.get("patient_type")))
            draw_card(390, 480, 155, 52, "CCN", facility["cms_certification_number_ccn"])

            draw_card(50, 415, 155, 52, "Previous Coverage", text_or_default(facility.get("previous_coverage")))
            draw_card(220, 415, 155, 52, "Provider Performance", text_or_default(facility.get("previous_provider_performance")))
            draw_card(390, 415, 155, 52, "Medical Coverage", text_or_default(facility.get("medical_coverage")))

            draw_card(50, 350, 495, 52, "MedElite History", text_or_default(facility.get("medelite_history")))

            # CMS Ratings heading
            pdf.setFillColorRGB(*ink)
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawString(50, 320, "CMS Ratings")

            # Rating card helper
            def rating_color(value):
                value = int(value) if value else 0
                if value >= 4:
                    return green
                if value == 3:
                    return gold
                if value == 2:
                    return orange
                return red

            def draw_rating_card(x, y, w, h, label, value):
                color = rating_color(value)

                pdf.setStrokeColorRGB(*sand)
                pdf.setFillColorRGB(1, 1, 1)
                pdf.roundRect(x, y, w, h, 12, fill=1, stroke=1)

                pdf.setFillColorRGB(*color)
                pdf.roundRect(x, y + h - 6, w, 6, 4, fill=1, stroke=0)

                pdf.setFillColorRGB(*muted)
                pdf.setFont("Helvetica-Bold", 7)
                pdf.drawString(x + 12, y + h - 22, label.upper())

                pdf.setFillColorRGB(*ink)
                pdf.setFont("Helvetica-Bold", 26)
                pdf.drawString(x + 12, y + 18, f"{value}/5")

            draw_rating_card(50, 245, 115, 65, "Overall", facility["overall_rating"])
            draw_rating_card(180, 245, 115, 65, "Health", facility["health_inspection_rating"])
            draw_rating_card(310, 245, 115, 65, "Staffing", facility["staffing_rating"])
            draw_rating_card(440, 245, 115, 65, "Quality", facility["qm_rating"])

            # Executive Summary
            pdf.setFillColorRGB(*ink)
            pdf.setFont("Helvetica-Bold", 14)
            pdf.drawString(50, 220, "Facility Snapshot")

            pdf.setFillColorRGB(*ink)
            pdf.setFont("Helvetica", 10)

            summary_occupancy = (
                f"Occupancy currently at {facility['occupancy']}%"
                if facility.get("occupancy")
                else "Occupancy data not provided"
            )

            pdf.drawString(60, 200, f"- {summary_occupancy}")
            pdf.drawString(60, 185, f"- Overall CMS Rating: {facility['overall_rating']}/5")
            pdf.drawString(60, 170, f"- Staffing Rating: {facility['staffing_rating']}/5")
            pdf.drawString(60, 155, f"- Medicare Care Compare profile linked below")

            # Medicare link
            care_compare_url = f"https://www.medicare.gov/care-compare/details/nursing-home/{facility['cms_certification_number_ccn']}"

            pdf.setFillColorRGB(*blue)
            pdf.setFont("Helvetica-Bold", 10)
            pdf.drawString(50, 125, "→ View Medicare Care Compare Profile")

            pdf.line(50, 122, 220, 122)

            pdf.linkURL(
                care_compare_url,
                (50, 120, 260, 135),
                relative=0
            )

            # Footer
            pdf.setFillColorRGB(*muted)
            pdf.setFont("Helvetica", 7)
            pdf.drawString(50, 45, "Source: CMS Provider Data and Medicare Care Compare")

            pdf.save()
            pdf_buffer.seek(0)

            return send_file(
                pdf_buffer,
                as_attachment=True,
                download_name=f"{facility['provider_name']}_assessment.pdf",
                mimetype="application/pdf"
            )
    
    if action == "docx":

            doc = Document()

            care_compare_url = (
                f"https://www.medicare.gov/care-compare/details/nursing-home/"
                f"{facility['cms_certification_number_ccn']}"
)
            # --------------------------------------------------
            # HEADER
            # --------------------------------------------------

            title = doc.add_paragraph()
            title.style = "Title"
            title.add_run("INFINITE — Managed by MEDELITE")

            subtitle = doc.add_paragraph()
            subtitle.style = "Heading 1"
            subtitle.add_run(
                f"FACILITY ASSESSMENT SNAPSHOT — {facility.get('state_abbrev', '')}"
            )

            doc.add_paragraph(
                f"Generated on {today} | MedElite Analytics"
            )

            doc.add_paragraph()

            # --------------------------------------------------
            # FACILITY
            # --------------------------------------------------

            doc.add_heading("Facility Overview", level=1)

            overview = doc.add_table(rows=6, cols=2)
            overview.style = "Table Grid"

            overview.cell(0,0).text = "Facility Name"
            overview.cell(0,1).text = facility["provider_name"]

            overview.cell(1,0).text = "Location"
            overview.cell(1,1).text = facility["location"]

            overview.cell(2,0).text = "CCN"
            overview.cell(2,1).text = facility["cms_certification_number_ccn"]

            overview.cell(3,0).text = "Certified Beds"
            overview.cell(3,1).text = str(facility["number_of_certified_beds"])

            overview.cell(4,0).text = "Current Census"
            overview.cell(4,1).text = str(facility.get("current_census") or "Not Provided")

            overview.cell(5,0).text = "Occupancy"
            overview.cell(5,1).text = f"{facility.get('occupancy')}%"

            doc.add_paragraph()

            # --------------------------------------------------
            # OPERATIONS
            # --------------------------------------------------

            doc.add_heading("Operational Inputs", level=1)

            ops = doc.add_table(rows=5, cols=2)
            ops.style = "Table Grid"

            ops.cell(0,0).text = "EMR"
            ops.cell(0,1).text = text_or_default(facility.get("emr"))

            ops.cell(1,0).text = "Patient Type"
            ops.cell(1,1).text = text_or_default(facility.get("patient_type"))

            ops.cell(2,0).text = "Previous Coverage"
            ops.cell(2,1).text = text_or_default(facility.get("previous_coverage"))

            ops.cell(3,0).text = "Provider Performance"
            ops.cell(3,1).text = text_or_default(
                facility.get("previous_provider_performance")
            )

            ops.cell(4,0).text = "Medical Coverage"
            ops.cell(4,1).text = text_or_default(
                facility.get("medical_coverage")
            )

            doc.add_paragraph()

            # --------------------------------------------------
            # RATINGS
            # --------------------------------------------------

            doc.add_heading("CMS Ratings", level=1)

            ratings = doc.add_table(rows=5, cols=3)
            ratings.style = "Medium Grid 1 Accent 1"

            ratings.cell(0,0).text = "Metric"
            ratings.cell(0,1).text = "Rating"
            ratings.cell(0,2).text = "Stars"

            ratings.cell(1,0).text = "Overall"
            ratings.cell(1,1).text = f"{facility['overall_rating']}/5"
            ratings.cell(1,2).text = "★" * int(facility["overall_rating"])

            ratings.cell(2,0).text = "Health Inspection"
            ratings.cell(2,1).text = f"{facility['health_inspection_rating']}/5"
            ratings.cell(2,2).text = "★" * int(facility["health_inspection_rating"])

            ratings.cell(3,0).text = "Staffing"
            ratings.cell(3,1).text = f"{facility['staffing_rating']}/5"
            ratings.cell(3,2).text = "★" * int(facility["staffing_rating"])

            ratings.cell(4,0).text = "Quality Care"
            ratings.cell(4,1).text = f"{facility['qm_rating']}/5"
            ratings.cell(4,2).text = "★" * int(facility["qm_rating"])

            doc.add_paragraph()

            # --------------------------------------------------
            # EXECUTIVE SUMMARY
            # --------------------------------------------------

            doc.add_heading("Executive Summary", level=1)

            doc.add_paragraph(
                f"Facility currently operates at {facility.get('occupancy')}% occupancy.",
                style="List Bullet"
            )

            doc.add_paragraph(
                f"Overall CMS Rating: {facility['overall_rating']}/5",
                style="List Bullet"
            )

            doc.add_paragraph(
                f"Staffing Rating: {facility['staffing_rating']}/5",
                style="List Bullet"
            )

            doc.add_paragraph(
                "Medicare Care Compare profile available below.",
                style="List Bullet"
            )

            # --------------------------------------------------
            # SOURCE
            # --------------------------------------------------

            doc.add_heading("Source", level=1)

            doc.add_paragraph(care_compare_url)

            doc_buffer = BytesIO()

            doc.save(doc_buffer)
            doc_buffer.seek(0)

            safe_name = facility["provider_name"].replace("/", "-")


            return send_file(
                doc_buffer,
                as_attachment=True,
                download_name=f"{safe_name}_Facility_Assessment.docx",
                mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )    
        

    return render_template(
        "index.html",
        facility=facility,
        form=request.form
        ) 


if __name__ == "__main__":
    app.run(debug=True, port=8000)
